### ISSUE TITLE
stacking implementation: investigate cross_val_predict

### ISSUE THREAD

**Issue by kmike** [TeamHG-Memex/soft404#4]
If I'm reading the code correctly, currently GradientBoostingClassifier is trained on the output of SGDClassifier, where predictions are for the same data as used for training this SGDClassifier. It means that there is some overfitting involved; probabilities returned by SGDClassifier may be of a different quality in real world, and GradientBoostingClassifier won't account for that. 

It doesn't always help (e.g. for formasaurus it didn't), but by using cross_val_predict we can try to get a more realistic input to GradientBoostingClassifier.

**Comment by lopuhin** [comment]
Thanks for the catch @kmike ! In fact, I never realised what is cross_val_predict good for before this  :)
I've got predictions with cross_val_predict in 92015ad, but still numeric features didn't improve any metrics once the text classifier part got better. But they are worth revisiting. Closing this for now, as there is no stacking currently.
